/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo_synch.v:1.1-59.10" *)
module synch_fifo_bram(clk, rst_n, wr_en, rd_en, data_in, full, empty, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_synch.v:33.45-33.58|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _219_;
  (* force_downto = 32'd1 *)
  (* src = "fifo_synch.v:44.27-44.40|fifo_synch.v:33.45-33.58|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _220_;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[0] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[1] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[2] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[3] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[4] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[5] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[6] ;
  (* src = "fifo_synch.v:19.26-19.30" *)
  wire [7:0] \bram[7] ;
  (* src = "fifo_synch.v:5.36-5.39" *)
  input clk;
  wire clk;
  (* src = "fifo_synch.v:9.36-9.43" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "fifo_synch.v:12.36-12.44" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "fifo_synch.v:11.36-11.41" *)
  output empty;
  wire empty;
  (* src = "fifo_synch.v:10.36-10.40" *)
  output full;
  wire full;
  (* src = "fifo_synch.v:8.36-8.41" *)
  input rd_en;
  wire rd_en;
  (* src = "fifo_synch.v:23.24-23.30" *)
  wire [3:0] rd_ptr;
  (* src = "fifo_synch.v:24.26-24.36" *)
  wire [2:0] rd_ptr_reg;
  (* src = "fifo_synch.v:6.36-6.41" *)
  input rst_n;
  wire rst_n;
  (* src = "fifo_synch.v:7.36-7.41" *)
  input wr_en;
  wire wr_en;
  (* src = "fifo_synch.v:22.24-22.30" *)
  wire [3:0] wr_ptr;
  INV_X1 _221_ (
    .A(rd_ptr[0]),
    .ZN(_080_)
  );
  INV_X1 _222_ (
    .A(rd_ptr[2]),
    .ZN(_081_)
  );
  INV_X1 _223_ (
    .A(wr_ptr[2]),
    .ZN(_082_)
  );
  INV_X1 _224_ (
    .A(_000_),
    .ZN(_083_)
  );
  XNOR2_X1 _225_ (
    .A(rd_ptr[1]),
    .B(wr_ptr[1]),
    .ZN(_084_)
  );
  XNOR2_X1 _226_ (
    .A(rd_ptr[0]),
    .B(wr_ptr[0]),
    .ZN(_085_)
  );
  XNOR2_X1 _227_ (
    .A(rd_ptr[2]),
    .B(wr_ptr[2]),
    .ZN(_086_)
  );
  XNOR2_X1 _228_ (
    .A(rd_ptr[3]),
    .B(wr_ptr[3]),
    .ZN(_087_)
  );
  XOR2_X1 _229_ (
    .A(rd_ptr[3]),
    .B(wr_ptr[3]),
    .Z(_088_)
  );
  NAND4_X1 _230_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .A4(_088_),
    .ZN(_089_)
  );
  INV_X1 _231_ (
    .A(_089_),
    .ZN(full)
  );
  AND2_X1 _232_ (
    .A1(wr_en),
    .A2(_089_),
    .ZN(_090_)
  );
  NAND4_X1 _233_ (
    .A1(_083_),
    .A2(rst_n),
    .A3(wr_en),
    .A4(_089_),
    .ZN(_091_)
  );
  NOR3_X1 _234_ (
    .A1(wr_ptr[0]),
    .A2(wr_ptr[1]),
    .A3(_091_),
    .ZN(_092_)
  );
  MUX2_X1 _235_ (
    .A(\bram[4] [1]),
    .B(data_in[1]),
    .S(_092_),
    .Z(_005_)
  );
  MUX2_X1 _236_ (
    .A(\bram[4] [2]),
    .B(data_in[2]),
    .S(_092_),
    .Z(_006_)
  );
  MUX2_X1 _237_ (
    .A(\bram[4] [3]),
    .B(data_in[3]),
    .S(_092_),
    .Z(_007_)
  );
  MUX2_X1 _238_ (
    .A(\bram[4] [4]),
    .B(data_in[4]),
    .S(_092_),
    .Z(_008_)
  );
  MUX2_X1 _239_ (
    .A(\bram[4] [5]),
    .B(data_in[5]),
    .S(_092_),
    .Z(_009_)
  );
  MUX2_X1 _240_ (
    .A(\bram[4] [6]),
    .B(data_in[6]),
    .S(_092_),
    .Z(_010_)
  );
  MUX2_X1 _241_ (
    .A(\bram[4] [7]),
    .B(data_in[7]),
    .S(_092_),
    .Z(_011_)
  );
  OR3_X1 _242_ (
    .A1(_219_[0]),
    .A2(wr_ptr[1]),
    .A3(_091_),
    .ZN(_093_)
  );
  MUX2_X1 _243_ (
    .A(data_in[0]),
    .B(\bram[5] [0]),
    .S(_093_),
    .Z(_012_)
  );
  MUX2_X1 _244_ (
    .A(data_in[1]),
    .B(\bram[5] [1]),
    .S(_093_),
    .Z(_013_)
  );
  MUX2_X1 _245_ (
    .A(data_in[2]),
    .B(\bram[5] [2]),
    .S(_093_),
    .Z(_014_)
  );
  MUX2_X1 _246_ (
    .A(data_in[3]),
    .B(\bram[5] [3]),
    .S(_093_),
    .Z(_015_)
  );
  MUX2_X1 _247_ (
    .A(data_in[4]),
    .B(\bram[5] [4]),
    .S(_093_),
    .Z(_016_)
  );
  MUX2_X1 _248_ (
    .A(data_in[5]),
    .B(\bram[5] [5]),
    .S(_093_),
    .Z(_017_)
  );
  MUX2_X1 _249_ (
    .A(data_in[6]),
    .B(\bram[5] [6]),
    .S(_093_),
    .Z(_018_)
  );
  MUX2_X1 _250_ (
    .A(data_in[7]),
    .B(\bram[5] [7]),
    .S(_093_),
    .Z(_019_)
  );
  OR3_X1 _251_ (
    .A1(wr_ptr[0]),
    .A2(_001_),
    .A3(_091_),
    .ZN(_094_)
  );
  MUX2_X1 _252_ (
    .A(data_in[0]),
    .B(\bram[6] [0]),
    .S(_094_),
    .Z(_020_)
  );
  MUX2_X1 _253_ (
    .A(data_in[1]),
    .B(\bram[6] [1]),
    .S(_094_),
    .Z(_021_)
  );
  MUX2_X1 _254_ (
    .A(data_in[2]),
    .B(\bram[6] [2]),
    .S(_094_),
    .Z(_022_)
  );
  MUX2_X1 _255_ (
    .A(data_in[3]),
    .B(\bram[6] [3]),
    .S(_094_),
    .Z(_023_)
  );
  MUX2_X1 _256_ (
    .A(data_in[4]),
    .B(\bram[6] [4]),
    .S(_094_),
    .Z(_024_)
  );
  MUX2_X1 _257_ (
    .A(data_in[5]),
    .B(\bram[6] [5]),
    .S(_094_),
    .Z(_025_)
  );
  MUX2_X1 _258_ (
    .A(data_in[6]),
    .B(\bram[6] [6]),
    .S(_094_),
    .Z(_026_)
  );
  MUX2_X1 _259_ (
    .A(data_in[7]),
    .B(\bram[6] [7]),
    .S(_094_),
    .Z(_027_)
  );
  NAND4_X1 _260_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .A4(_087_),
    .ZN(_095_)
  );
  INV_X1 _261_ (
    .A(_095_),
    .ZN(empty)
  );
  NAND2_X1 _262_ (
    .A1(rd_en),
    .A2(_095_),
    .ZN(_096_)
  );
  MUX2_X1 _263_ (
    .A(_220_[0]),
    .B(rd_ptr[0]),
    .S(_096_),
    .Z(_028_)
  );
  OR2_X1 _264_ (
    .A1(rd_ptr[1]),
    .A2(_096_),
    .ZN(_097_)
  );
  OAI21_X1 _265_ (
    .A(rd_ptr[1]),
    .B1(_096_),
    .B2(_080_),
    .ZN(_098_)
  );
  OAI21_X1 _266_ (
    .A(_098_),
    .B1(_097_),
    .B2(_080_),
    .ZN(_029_)
  );
  NAND2_X1 _267_ (
    .A1(rd_ptr[0]),
    .A2(rd_ptr[1]),
    .ZN(_099_)
  );
  NOR2_X1 _268_ (
    .A1(_096_),
    .A2(_099_),
    .ZN(_100_)
  );
  XNOR2_X1 _269_ (
    .A(_081_),
    .B(_100_),
    .ZN(_030_)
  );
  NOR3_X1 _270_ (
    .A1(_081_),
    .A2(_096_),
    .A3(_099_),
    .ZN(_101_)
  );
  XOR2_X1 _271_ (
    .A(rd_ptr[3]),
    .B(_101_),
    .Z(_031_)
  );
  OR3_X1 _272_ (
    .A1(_219_[0]),
    .A2(_001_),
    .A3(_091_),
    .ZN(_102_)
  );
  MUX2_X1 _273_ (
    .A(data_in[0]),
    .B(\bram[7] [0]),
    .S(_102_),
    .Z(_032_)
  );
  MUX2_X1 _274_ (
    .A(data_in[1]),
    .B(\bram[7] [1]),
    .S(_102_),
    .Z(_033_)
  );
  MUX2_X1 _275_ (
    .A(data_in[2]),
    .B(\bram[7] [2]),
    .S(_102_),
    .Z(_034_)
  );
  MUX2_X1 _276_ (
    .A(data_in[3]),
    .B(\bram[7] [3]),
    .S(_102_),
    .Z(_035_)
  );
  MUX2_X1 _277_ (
    .A(data_in[4]),
    .B(\bram[7] [4]),
    .S(_102_),
    .Z(_036_)
  );
  MUX2_X1 _278_ (
    .A(data_in[5]),
    .B(\bram[7] [5]),
    .S(_102_),
    .Z(_037_)
  );
  MUX2_X1 _279_ (
    .A(data_in[6]),
    .B(\bram[7] [6]),
    .S(_102_),
    .Z(_038_)
  );
  MUX2_X1 _280_ (
    .A(data_in[7]),
    .B(\bram[7] [7]),
    .S(_102_),
    .Z(_039_)
  );
  MUX2_X1 _281_ (
    .A(rd_ptr[0]),
    .B(rd_ptr_reg[0]),
    .S(_096_),
    .Z(_040_)
  );
  MUX2_X1 _282_ (
    .A(rd_ptr[1]),
    .B(rd_ptr_reg[1]),
    .S(_096_),
    .Z(_041_)
  );
  MUX2_X1 _283_ (
    .A(rd_ptr[2]),
    .B(rd_ptr_reg[2]),
    .S(_096_),
    .Z(_042_)
  );
  MUX2_X1 _284_ (
    .A(wr_ptr[0]),
    .B(_219_[0]),
    .S(_090_),
    .Z(_043_)
  );
  XOR2_X1 _285_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Z(_103_)
  );
  MUX2_X1 _286_ (
    .A(wr_ptr[1]),
    .B(_103_),
    .S(_090_),
    .Z(_044_)
  );
  NAND3_X1 _287_ (
    .A1(wr_ptr[0]),
    .A2(wr_ptr[1]),
    .A3(_090_),
    .ZN(_104_)
  );
  NAND4_X1 _288_ (
    .A1(wr_ptr[0]),
    .A2(wr_ptr[1]),
    .A3(wr_ptr[2]),
    .A4(_090_),
    .ZN(_105_)
  );
  XNOR2_X1 _289_ (
    .A(wr_ptr[2]),
    .B(_104_),
    .ZN(_045_)
  );
  XNOR2_X1 _290_ (
    .A(wr_ptr[3]),
    .B(_105_),
    .ZN(_046_)
  );
  NAND4_X1 _291_ (
    .A1(_082_),
    .A2(rst_n),
    .A3(wr_en),
    .A4(_089_),
    .ZN(_106_)
  );
  NOR3_X1 _292_ (
    .A1(wr_ptr[0]),
    .A2(wr_ptr[1]),
    .A3(_106_),
    .ZN(_107_)
  );
  MUX2_X1 _293_ (
    .A(\bram[0] [0]),
    .B(data_in[0]),
    .S(_107_),
    .Z(_047_)
  );
  MUX2_X1 _294_ (
    .A(\bram[0] [1]),
    .B(data_in[1]),
    .S(_107_),
    .Z(_048_)
  );
  MUX2_X1 _295_ (
    .A(\bram[0] [2]),
    .B(data_in[2]),
    .S(_107_),
    .Z(_049_)
  );
  MUX2_X1 _296_ (
    .A(\bram[0] [3]),
    .B(data_in[3]),
    .S(_107_),
    .Z(_050_)
  );
  MUX2_X1 _297_ (
    .A(\bram[0] [4]),
    .B(data_in[4]),
    .S(_107_),
    .Z(_051_)
  );
  MUX2_X1 _298_ (
    .A(\bram[0] [5]),
    .B(data_in[5]),
    .S(_107_),
    .Z(_052_)
  );
  MUX2_X1 _299_ (
    .A(\bram[0] [6]),
    .B(data_in[6]),
    .S(_107_),
    .Z(_053_)
  );
  MUX2_X1 _300_ (
    .A(\bram[0] [7]),
    .B(data_in[7]),
    .S(_107_),
    .Z(_054_)
  );
  OR3_X1 _301_ (
    .A1(_219_[0]),
    .A2(wr_ptr[1]),
    .A3(_106_),
    .ZN(_108_)
  );
  MUX2_X1 _302_ (
    .A(data_in[0]),
    .B(\bram[1] [0]),
    .S(_108_),
    .Z(_055_)
  );
  MUX2_X1 _303_ (
    .A(data_in[1]),
    .B(\bram[1] [1]),
    .S(_108_),
    .Z(_056_)
  );
  MUX2_X1 _304_ (
    .A(data_in[2]),
    .B(\bram[1] [2]),
    .S(_108_),
    .Z(_057_)
  );
  MUX2_X1 _305_ (
    .A(data_in[3]),
    .B(\bram[1] [3]),
    .S(_108_),
    .Z(_058_)
  );
  MUX2_X1 _306_ (
    .A(data_in[4]),
    .B(\bram[1] [4]),
    .S(_108_),
    .Z(_059_)
  );
  MUX2_X1 _307_ (
    .A(data_in[5]),
    .B(\bram[1] [5]),
    .S(_108_),
    .Z(_060_)
  );
  MUX2_X1 _308_ (
    .A(data_in[6]),
    .B(\bram[1] [6]),
    .S(_108_),
    .Z(_061_)
  );
  MUX2_X1 _309_ (
    .A(data_in[7]),
    .B(\bram[1] [7]),
    .S(_108_),
    .Z(_062_)
  );
  OR3_X1 _310_ (
    .A1(wr_ptr[0]),
    .A2(_001_),
    .A3(_106_),
    .ZN(_109_)
  );
  MUX2_X1 _311_ (
    .A(data_in[0]),
    .B(\bram[2] [0]),
    .S(_109_),
    .Z(_063_)
  );
  MUX2_X1 _312_ (
    .A(data_in[1]),
    .B(\bram[2] [1]),
    .S(_109_),
    .Z(_064_)
  );
  MUX2_X1 _313_ (
    .A(data_in[2]),
    .B(\bram[2] [2]),
    .S(_109_),
    .Z(_065_)
  );
  MUX2_X1 _314_ (
    .A(data_in[3]),
    .B(\bram[2] [3]),
    .S(_109_),
    .Z(_066_)
  );
  MUX2_X1 _315_ (
    .A(data_in[4]),
    .B(\bram[2] [4]),
    .S(_109_),
    .Z(_067_)
  );
  MUX2_X1 _316_ (
    .A(data_in[5]),
    .B(\bram[2] [5]),
    .S(_109_),
    .Z(_068_)
  );
  MUX2_X1 _317_ (
    .A(data_in[6]),
    .B(\bram[2] [6]),
    .S(_109_),
    .Z(_069_)
  );
  MUX2_X1 _318_ (
    .A(data_in[7]),
    .B(\bram[2] [7]),
    .S(_109_),
    .Z(_070_)
  );
  OR3_X1 _319_ (
    .A1(_219_[0]),
    .A2(_001_),
    .A3(_106_),
    .ZN(_110_)
  );
  MUX2_X1 _320_ (
    .A(data_in[0]),
    .B(\bram[3] [0]),
    .S(_110_),
    .Z(_071_)
  );
  MUX2_X1 _321_ (
    .A(data_in[1]),
    .B(\bram[3] [1]),
    .S(_110_),
    .Z(_072_)
  );
  MUX2_X1 _322_ (
    .A(data_in[2]),
    .B(\bram[3] [2]),
    .S(_110_),
    .Z(_073_)
  );
  MUX2_X1 _323_ (
    .A(data_in[3]),
    .B(\bram[3] [3]),
    .S(_110_),
    .Z(_074_)
  );
  MUX2_X1 _324_ (
    .A(data_in[4]),
    .B(\bram[3] [4]),
    .S(_110_),
    .Z(_075_)
  );
  MUX2_X1 _325_ (
    .A(data_in[5]),
    .B(\bram[3] [5]),
    .S(_110_),
    .Z(_076_)
  );
  MUX2_X1 _326_ (
    .A(data_in[6]),
    .B(\bram[3] [6]),
    .S(_110_),
    .Z(_077_)
  );
  MUX2_X1 _327_ (
    .A(data_in[7]),
    .B(\bram[3] [7]),
    .S(_110_),
    .Z(_078_)
  );
  MUX2_X1 _328_ (
    .A(\bram[4] [0]),
    .B(data_in[0]),
    .S(_092_),
    .Z(_079_)
  );
  NOR3_X1 _329_ (
    .A1(rd_ptr_reg[2]),
    .A2(_004_),
    .A3(_003_),
    .ZN(_111_)
  );
  NOR3_X1 _330_ (
    .A1(rd_ptr_reg[0]),
    .A2(rd_ptr_reg[2]),
    .A3(_003_),
    .ZN(_112_)
  );
  AOI22_X1 _331_ (
    .A1(\bram[3] [0]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [0]),
    .ZN(_113_)
  );
  NOR3_X1 _332_ (
    .A1(rd_ptr_reg[1]),
    .A2(rd_ptr_reg[2]),
    .A3(_004_),
    .ZN(_114_)
  );
  NOR3_X1 _333_ (
    .A1(rd_ptr_reg[1]),
    .A2(_002_),
    .A3(_004_),
    .ZN(_115_)
  );
  AOI22_X1 _334_ (
    .A1(\bram[1] [0]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [0]),
    .ZN(_116_)
  );
  NOR3_X1 _335_ (
    .A1(_002_),
    .A2(_004_),
    .A3(_003_),
    .ZN(_117_)
  );
  NOR3_X1 _336_ (
    .A1(rd_ptr_reg[0]),
    .A2(rd_ptr_reg[1]),
    .A3(rd_ptr_reg[2]),
    .ZN(_118_)
  );
  AOI22_X1 _337_ (
    .A1(\bram[7] [0]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [0]),
    .ZN(_119_)
  );
  NOR3_X1 _338_ (
    .A1(rd_ptr_reg[0]),
    .A2(_002_),
    .A3(_003_),
    .ZN(_120_)
  );
  NOR3_X1 _339_ (
    .A1(rd_ptr_reg[0]),
    .A2(rd_ptr_reg[1]),
    .A3(_002_),
    .ZN(_121_)
  );
  AOI22_X1 _340_ (
    .A1(\bram[6] [0]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [0]),
    .ZN(_122_)
  );
  NAND4_X1 _341_ (
    .A1(_113_),
    .A2(_116_),
    .A3(_119_),
    .A4(_122_),
    .ZN(data_out[0])
  );
  AOI22_X1 _342_ (
    .A1(\bram[3] [1]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [1]),
    .ZN(_123_)
  );
  AOI22_X1 _343_ (
    .A1(\bram[1] [1]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [1]),
    .ZN(_124_)
  );
  AOI22_X1 _344_ (
    .A1(\bram[7] [1]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [1]),
    .ZN(_125_)
  );
  AOI22_X1 _345_ (
    .A1(\bram[6] [1]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [1]),
    .ZN(_126_)
  );
  NAND4_X1 _346_ (
    .A1(_123_),
    .A2(_124_),
    .A3(_125_),
    .A4(_126_),
    .ZN(data_out[1])
  );
  AOI22_X1 _347_ (
    .A1(\bram[3] [2]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [2]),
    .ZN(_127_)
  );
  AOI22_X1 _348_ (
    .A1(\bram[1] [2]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [2]),
    .ZN(_128_)
  );
  AOI22_X1 _349_ (
    .A1(\bram[7] [2]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [2]),
    .ZN(_129_)
  );
  AOI22_X1 _350_ (
    .A1(\bram[6] [2]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [2]),
    .ZN(_130_)
  );
  NAND4_X1 _351_ (
    .A1(_127_),
    .A2(_128_),
    .A3(_129_),
    .A4(_130_),
    .ZN(data_out[2])
  );
  AOI22_X1 _352_ (
    .A1(\bram[3] [3]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [3]),
    .ZN(_131_)
  );
  AOI22_X1 _353_ (
    .A1(\bram[1] [3]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [3]),
    .ZN(_132_)
  );
  AOI22_X1 _354_ (
    .A1(\bram[7] [3]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [3]),
    .ZN(_133_)
  );
  AOI22_X1 _355_ (
    .A1(\bram[6] [3]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [3]),
    .ZN(_134_)
  );
  NAND4_X1 _356_ (
    .A1(_131_),
    .A2(_132_),
    .A3(_133_),
    .A4(_134_),
    .ZN(data_out[3])
  );
  AOI22_X1 _357_ (
    .A1(\bram[3] [4]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [4]),
    .ZN(_135_)
  );
  AOI22_X1 _358_ (
    .A1(\bram[1] [4]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [4]),
    .ZN(_136_)
  );
  AOI22_X1 _359_ (
    .A1(\bram[7] [4]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [4]),
    .ZN(_137_)
  );
  AOI22_X1 _360_ (
    .A1(\bram[6] [4]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [4]),
    .ZN(_138_)
  );
  NAND4_X1 _361_ (
    .A1(_135_),
    .A2(_136_),
    .A3(_137_),
    .A4(_138_),
    .ZN(data_out[4])
  );
  AOI22_X1 _362_ (
    .A1(\bram[3] [5]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [5]),
    .ZN(_139_)
  );
  AOI22_X1 _363_ (
    .A1(\bram[1] [5]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [5]),
    .ZN(_140_)
  );
  AOI22_X1 _364_ (
    .A1(\bram[7] [5]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [5]),
    .ZN(_141_)
  );
  AOI22_X1 _365_ (
    .A1(\bram[6] [5]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [5]),
    .ZN(_142_)
  );
  NAND4_X1 _366_ (
    .A1(_139_),
    .A2(_140_),
    .A3(_141_),
    .A4(_142_),
    .ZN(data_out[5])
  );
  AOI22_X1 _367_ (
    .A1(\bram[3] [6]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [6]),
    .ZN(_143_)
  );
  AOI22_X1 _368_ (
    .A1(\bram[1] [6]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [6]),
    .ZN(_144_)
  );
  AOI22_X1 _369_ (
    .A1(\bram[7] [6]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [6]),
    .ZN(_145_)
  );
  AOI22_X1 _370_ (
    .A1(\bram[6] [6]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [6]),
    .ZN(_146_)
  );
  NAND4_X1 _371_ (
    .A1(_143_),
    .A2(_144_),
    .A3(_145_),
    .A4(_146_),
    .ZN(data_out[6])
  );
  AOI22_X1 _372_ (
    .A1(\bram[3] [7]),
    .A2(_111_),
    .B1(_112_),
    .B2(\bram[2] [7]),
    .ZN(_147_)
  );
  AOI22_X1 _373_ (
    .A1(\bram[1] [7]),
    .A2(_114_),
    .B1(_115_),
    .B2(\bram[5] [7]),
    .ZN(_148_)
  );
  AOI22_X1 _374_ (
    .A1(\bram[7] [7]),
    .A2(_117_),
    .B1(_118_),
    .B2(\bram[0] [7]),
    .ZN(_149_)
  );
  AOI22_X1 _375_ (
    .A1(\bram[6] [7]),
    .A2(_120_),
    .B1(_121_),
    .B2(\bram[4] [7]),
    .ZN(_150_)
  );
  NAND4_X1 _376_ (
    .A1(_147_),
    .A2(_148_),
    .A3(_149_),
    .A4(_150_),
    .ZN(data_out[7])
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _377_ (
    .CK(clk),
    .D(_032_),
    .Q(\bram[7] [0]),
    .QN(_218_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _378_ (
    .CK(clk),
    .D(_033_),
    .Q(\bram[7] [1]),
    .QN(_217_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _379_ (
    .CK(clk),
    .D(_034_),
    .Q(\bram[7] [2]),
    .QN(_216_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _380_ (
    .CK(clk),
    .D(_035_),
    .Q(\bram[7] [3]),
    .QN(_215_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _381_ (
    .CK(clk),
    .D(_036_),
    .Q(\bram[7] [4]),
    .QN(_214_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _382_ (
    .CK(clk),
    .D(_037_),
    .Q(\bram[7] [5]),
    .QN(_213_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _383_ (
    .CK(clk),
    .D(_038_),
    .Q(\bram[7] [6]),
    .QN(_212_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _384_ (
    .CK(clk),
    .D(_039_),
    .Q(\bram[7] [7]),
    .QN(_211_)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _385_ (
    .CK(clk),
    .D(_040_),
    .Q(rd_ptr_reg[0]),
    .QN(_004_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _386_ (
    .CK(clk),
    .D(_041_),
    .Q(rd_ptr_reg[1]),
    .QN(_003_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _387_ (
    .CK(clk),
    .D(_042_),
    .Q(rd_ptr_reg[2]),
    .QN(_002_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFFR_X1 _388_ (
    .CK(clk),
    .D(_043_),
    .Q(wr_ptr[0]),
    .QN(_219_[0]),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFFR_X1 _389_ (
    .CK(clk),
    .D(_044_),
    .Q(wr_ptr[1]),
    .QN(_001_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFFR_X1 _390_ (
    .CK(clk),
    .D(_045_),
    .Q(wr_ptr[2]),
    .QN(_000_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFFR_X1 _391_ (
    .CK(clk),
    .D(_046_),
    .Q(wr_ptr[3]),
    .QN(_210_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _392_ (
    .CK(clk),
    .D(_047_),
    .Q(\bram[0] [0]),
    .QN(_209_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _393_ (
    .CK(clk),
    .D(_048_),
    .Q(\bram[0] [1]),
    .QN(_208_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _394_ (
    .CK(clk),
    .D(_049_),
    .Q(\bram[0] [2]),
    .QN(_207_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _395_ (
    .CK(clk),
    .D(_050_),
    .Q(\bram[0] [3]),
    .QN(_206_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _396_ (
    .CK(clk),
    .D(_051_),
    .Q(\bram[0] [4]),
    .QN(_205_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _397_ (
    .CK(clk),
    .D(_052_),
    .Q(\bram[0] [5]),
    .QN(_204_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _398_ (
    .CK(clk),
    .D(_053_),
    .Q(\bram[0] [6]),
    .QN(_203_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _399_ (
    .CK(clk),
    .D(_054_),
    .Q(\bram[0] [7]),
    .QN(_202_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _400_ (
    .CK(clk),
    .D(_055_),
    .Q(\bram[1] [0]),
    .QN(_201_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _401_ (
    .CK(clk),
    .D(_056_),
    .Q(\bram[1] [1]),
    .QN(_200_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _402_ (
    .CK(clk),
    .D(_057_),
    .Q(\bram[1] [2]),
    .QN(_199_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _403_ (
    .CK(clk),
    .D(_058_),
    .Q(\bram[1] [3]),
    .QN(_198_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _404_ (
    .CK(clk),
    .D(_059_),
    .Q(\bram[1] [4]),
    .QN(_197_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _405_ (
    .CK(clk),
    .D(_060_),
    .Q(\bram[1] [5]),
    .QN(_196_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _406_ (
    .CK(clk),
    .D(_061_),
    .Q(\bram[1] [6]),
    .QN(_195_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _407_ (
    .CK(clk),
    .D(_062_),
    .Q(\bram[1] [7]),
    .QN(_194_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _408_ (
    .CK(clk),
    .D(_063_),
    .Q(\bram[2] [0]),
    .QN(_193_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _409_ (
    .CK(clk),
    .D(_064_),
    .Q(\bram[2] [1]),
    .QN(_192_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _410_ (
    .CK(clk),
    .D(_065_),
    .Q(\bram[2] [2]),
    .QN(_191_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _411_ (
    .CK(clk),
    .D(_066_),
    .Q(\bram[2] [3]),
    .QN(_190_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _412_ (
    .CK(clk),
    .D(_067_),
    .Q(\bram[2] [4]),
    .QN(_189_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _413_ (
    .CK(clk),
    .D(_068_),
    .Q(\bram[2] [5]),
    .QN(_188_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _414_ (
    .CK(clk),
    .D(_069_),
    .Q(\bram[2] [6]),
    .QN(_187_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _415_ (
    .CK(clk),
    .D(_070_),
    .Q(\bram[2] [7]),
    .QN(_186_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _416_ (
    .CK(clk),
    .D(_071_),
    .Q(\bram[3] [0]),
    .QN(_185_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _417_ (
    .CK(clk),
    .D(_072_),
    .Q(\bram[3] [1]),
    .QN(_184_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _418_ (
    .CK(clk),
    .D(_073_),
    .Q(\bram[3] [2]),
    .QN(_183_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _419_ (
    .CK(clk),
    .D(_074_),
    .Q(\bram[3] [3]),
    .QN(_182_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _420_ (
    .CK(clk),
    .D(_075_),
    .Q(\bram[3] [4]),
    .QN(_181_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _421_ (
    .CK(clk),
    .D(_076_),
    .Q(\bram[3] [5]),
    .QN(_180_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _422_ (
    .CK(clk),
    .D(_077_),
    .Q(\bram[3] [6]),
    .QN(_179_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _423_ (
    .CK(clk),
    .D(_078_),
    .Q(\bram[3] [7]),
    .QN(_178_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _424_ (
    .CK(clk),
    .D(_079_),
    .Q(\bram[4] [0]),
    .QN(_177_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _425_ (
    .CK(clk),
    .D(_005_),
    .Q(\bram[4] [1]),
    .QN(_176_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _426_ (
    .CK(clk),
    .D(_006_),
    .Q(\bram[4] [2]),
    .QN(_175_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _427_ (
    .CK(clk),
    .D(_007_),
    .Q(\bram[4] [3]),
    .QN(_174_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _428_ (
    .CK(clk),
    .D(_008_),
    .Q(\bram[4] [4]),
    .QN(_173_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _429_ (
    .CK(clk),
    .D(_009_),
    .Q(\bram[4] [5]),
    .QN(_172_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _430_ (
    .CK(clk),
    .D(_010_),
    .Q(\bram[4] [6]),
    .QN(_171_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _431_ (
    .CK(clk),
    .D(_011_),
    .Q(\bram[4] [7]),
    .QN(_170_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _432_ (
    .CK(clk),
    .D(_012_),
    .Q(\bram[5] [0]),
    .QN(_169_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _433_ (
    .CK(clk),
    .D(_013_),
    .Q(\bram[5] [1]),
    .QN(_168_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _434_ (
    .CK(clk),
    .D(_014_),
    .Q(\bram[5] [2]),
    .QN(_167_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _435_ (
    .CK(clk),
    .D(_015_),
    .Q(\bram[5] [3]),
    .QN(_166_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _436_ (
    .CK(clk),
    .D(_016_),
    .Q(\bram[5] [4]),
    .QN(_165_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _437_ (
    .CK(clk),
    .D(_017_),
    .Q(\bram[5] [5]),
    .QN(_164_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _438_ (
    .CK(clk),
    .D(_018_),
    .Q(\bram[5] [6]),
    .QN(_163_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _439_ (
    .CK(clk),
    .D(_019_),
    .Q(\bram[5] [7]),
    .QN(_162_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _440_ (
    .CK(clk),
    .D(_020_),
    .Q(\bram[6] [0]),
    .QN(_161_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _441_ (
    .CK(clk),
    .D(_021_),
    .Q(\bram[6] [1]),
    .QN(_160_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _442_ (
    .CK(clk),
    .D(_022_),
    .Q(\bram[6] [2]),
    .QN(_159_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _443_ (
    .CK(clk),
    .D(_023_),
    .Q(\bram[6] [3]),
    .QN(_158_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _444_ (
    .CK(clk),
    .D(_024_),
    .Q(\bram[6] [4]),
    .QN(_157_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _445_ (
    .CK(clk),
    .D(_025_),
    .Q(\bram[6] [5]),
    .QN(_156_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _446_ (
    .CK(clk),
    .D(_026_),
    .Q(\bram[6] [6]),
    .QN(_155_)
  );
  (* src = "fifo_synch.v:27.5-35.8" *)
  DFF_X1 _447_ (
    .CK(clk),
    .D(_027_),
    .Q(\bram[6] [7]),
    .QN(_154_)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _448_ (
    .CK(clk),
    .D(_028_),
    .Q(rd_ptr[0]),
    .QN(_220_[0]),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _449_ (
    .CK(clk),
    .D(_029_),
    .Q(rd_ptr[1]),
    .QN(_153_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _450_ (
    .CK(clk),
    .D(_030_),
    .Q(rd_ptr[2]),
    .QN(_152_),
    .RN(rst_n)
  );
  (* src = "fifo_synch.v:38.5-47.8" *)
  DFFR_X1 _451_ (
    .CK(clk),
    .D(_031_),
    .Q(rd_ptr[3]),
    .QN(_151_),
    .RN(rst_n)
  );
  assign _219_[3:1] = wr_ptr[3:1];
  assign _220_[3:1] = rd_ptr[3:1];
endmodule
